sap.ui.define(["sap/ui/model/json/JSONModel", "sap/ui/Device"], function (JSONModel, Device) {
  "use strict";

  return {
    /**
     * Provides runtime information for the device the UI5 app is running on as a JSONModel.
     * @returns {sap.ui.model.json.JSONModel} The device model.
     */
    createDeviceModel: function () {
      var oModel = new JSONModel(Device);
      oModel.setDefaultBindingMode("OneWay");
      return oModel;
    },

    // createTrasferimentoMagazzinoModel() {
    //   return new JSONModel({
    //     step1: {
    //       enabled: true,
    //       magazzino: {
    //         lgort: "",
    //         tipo: "",
    //       },
    //       materiale: {
    //         matnr: "",
    //       },
    //     },
    //     step2: {
    //       enabled: false,
    //       materiale: {
    //         werks: "3980",
    //         lgort: "0001",
    //         matnr: "105555",
    //         maktx: "PIEDE REGOLABILE M12 H102",
    //       },
    //       list: {
    //         items: [
    //           {
    //             vlpla: "TERRA",
    //             labst: "152",
    //             meins: "PZ",
    //           },
    //           {
    //             vlpla: "03-18-04",
    //             labst: "500",
    //             meins: "PZ",
    //           },
    //         ],
    //       },
    //     },
    //     step3: {
    //       enabled: false,
    //       magazzino: {
    //         werks: "",
    //         lgort: "",
    //         tipo: "",
    //       },
    //       materiale: {
    //         matnr: "",
    //         maktx: "",
    //         vlpla: "",
    //         labst: "",
    //         meins: "",
    //       },
    //       new_magazzino: {
    //         lgort: "",
    //       },
    //     },
    //     step4: {
    //       enabled: false,
    //       magazzino: {
    //         werks: "",
    //         lgort: "",
    //         tipo: "",
    //       },
    //       materiale: {
    //         matnr: "",
    //         maktx: "",
    //         vlpla: "",
    //         labst: "",
    //         meins: "",
    //         nsola: ""
    //       },
    //       new_magazzino: {
    //         werks: "",
    //         lgort: "",
    //         tipo: "",
    //       },
    //     },
    //   });
    // },

    _mokGetInfo: function () {
      return new JSONModel({
        info: { Werks: "0001", Lgtyp: "004" },
        User: "MHD_RM_3980",
      });
    },

    _mokGetQuantity: function () {
      return new JSONModel([
        {
          WmList: {
            Agsta: "",
            Altme: "",
            Anzl1: "",
            Anzl2: "",
            Aufnr: "2266862",
            AufnrPos: "20",
            Ausme: "0",
            Bestq: "",
            Charg: "",
            Erfmg: "",
            Fullgpla: false,
            Hell: false,
            Lenum: "",
            Lety1: "",
            Lety2: "",
            Lety_1: "",
            Lety_2: "",
            Lgbe1: "",
            Lgbe2: "",
            Lgnum: "398",
            Lgort: "0001",
            Lgpla: "VETRI08",
            Lgtyp: "004",
            Lhme1: "",
            Lhme2: "",
            Lhmg1: "",
            Lhmg1Txt: "",
            Lhmg2: "",
            Lmen1: "",
            Lmen2: "",
            Lptyp: "",
            Lqnum: "3001804207",
            Ltkza: "",
            Ltkze: "",
            Maktx: "VETRO ANTIAP BST NF PAR.",
            Matnr: "77070000",
            Mblnr: "",
            Meins: "PZ",
            Menge: "1",
            MengeTxt: "",
            Mjahr: "",
            Msehi: "PZ",
            Mtart: "ZFER",
            Nlenr: "",
            Nlpla: "",
            Nltyp: "",
            Nppos: "",
            Schgt: false,
            Sernr: "",
            Sobkz: "E",
            Sonum: "0002266862000020",
            Squit: false,
            Tamea: "",
            Tamen: "",
            TamenTxt: "",
            Tanum: "",
            Tapos: "",
            Tbnum: "",
            Tbpos: "",
            Verme: "",
            VermeTxt: "1 PZ",
            Vlenr: "",
            Vlpla: "",
            Vltyp: "",
            Wdatu: "20250613",
            Werks: "3980",
          },
        },
        {
          WmList: {
            Agsta: "",
            Altme: "",
            Anzl1: "",
            Anzl2: "",
            Aufnr: "2266862",
            AufnrPos: "20",
            Ausme: "0",
            Bestq: "",
            Charg: "",
            Erfmg: "",
            Fullgpla: false,
            Hell: false,
            Lenum: "",
            Lety1: "",
            Lety2: "",
            Lety_1: "",
            Lety_2: "",
            Lgbe1: "",
            Lgbe2: "",
            Lgnum: "398",
            Lgort: "0001",
            Lgpla: "VETRI08",
            Lgtyp: "004",
            Lhme1: "",
            Lhme2: "",
            Lhmg1: "",
            Lhmg1Txt: "",
            Lhmg2: "",
            Lmen1: "",
            Lmen2: "",
            Lptyp: "",
            Lqnum: "3001804207",
            Ltkza: "",
            Ltkze: "",
            Maktx: "VETRO ANTIAP BST NF PAR.",
            Matnr: "77070000",
            Mblnr: "",
            Meins: "PZ",
            Menge: "1",
            MengeTxt: "",
            Mjahr: "",
            Msehi: "PZ",
            Mtart: "ZFER",
            Nlenr: "",
            Nlpla: "",
            Nltyp: "",
            Nppos: "",
            Schgt: false,
            Sernr: "",
            Sobkz: "E",
            Sonum: "0002266862000020",
            Squit: false,
            Tamea: "",
            Tamen: "",
            TamenTxt: "",
            Tanum: "",
            Tapos: "",
            Tbnum: "",
            Tbpos: "",
            Verme: "",
            VermeTxt: "1 PZ",
            Vlenr: "",
            Vlpla: "",
            Vltyp: "",
            Wdatu: "20250613",
            Werks: "3980",
          },
        },
        {
          WmList: {
            Agsta: "",
            Altme: "",
            Anzl1: "",
            Anzl2: "",
            Aufnr: "2266862",
            AufnrPos: "20",
            Ausme: "0",
            Bestq: "",
            Charg: "",
            Erfmg: "",
            Fullgpla: false,
            Hell: false,
            Lenum: "",
            Lety1: "",
            Lety2: "",
            Lety_1: "",
            Lety_2: "",
            Lgbe1: "",
            Lgbe2: "",
            Lgnum: "398",
            Lgort: "0001",
            Lgpla: "VETRI08",
            Lgtyp: "004",
            Lhme1: "",
            Lhme2: "",
            Lhmg1: "",
            Lhmg1Txt: "",
            Lhmg2: "",
            Lmen1: "",
            Lmen2: "",
            Lptyp: "",
            Lqnum: "3001804207",
            Ltkza: "",
            Ltkze: "",
            Maktx: "VETRO ANTIAP BST NF PAR.",
            Matnr: "77070000",
            Mblnr: "",
            Meins: "PZ",
            Menge: "1",
            MengeTxt: "",
            Mjahr: "",
            Msehi: "PZ",
            Mtart: "ZFER",
            Nlenr: "",
            Nlpla: "",
            Nltyp: "",
            Nppos: "",
            Schgt: false,
            Sernr: "",
            Sobkz: "E",
            Sonum: "0002266862000020",
            Squit: false,
            Tamea: "",
            Tamen: "",
            TamenTxt: "",
            Tanum: "",
            Tapos: "",
            Tbnum: "",
            Tbpos: "",
            Verme: "",
            VermeTxt: "1 PZ",
            Vlenr: "",
            Vlpla: "",
            Vltyp: "",
            Wdatu: "20250613",
            Werks: "3980",
          },
        },
        {
          WmList: {
            Agsta: "",
            Altme: "",
            Anzl1: "",
            Anzl2: "",
            Aufnr: "2266862",
            AufnrPos: "20",
            Ausme: "0",
            Bestq: "",
            Charg: "",
            Erfmg: "",
            Fullgpla: false,
            Hell: false,
            Lenum: "",
            Lety1: "",
            Lety2: "",
            Lety_1: "",
            Lety_2: "",
            Lgbe1: "",
            Lgbe2: "",
            Lgnum: "398",
            Lgort: "0001",
            Lgpla: "VETRI08",
            Lgtyp: "004",
            Lhme1: "",
            Lhme2: "",
            Lhmg1: "",
            Lhmg1Txt: "",
            Lhmg2: "",
            Lmen1: "",
            Lmen2: "",
            Lptyp: "",
            Lqnum: "3001804207",
            Ltkza: "",
            Ltkze: "",
            Maktx: "VETRO ANTIAP BST NF PAR.",
            Matnr: "77070000",
            Mblnr: "",
            Meins: "PZ",
            Menge: "1",
            MengeTxt: "",
            Mjahr: "",
            Msehi: "PZ",
            Mtart: "ZFER",
            Nlenr: "",
            Nlpla: "",
            Nltyp: "",
            Nppos: "",
            Schgt: false,
            Sernr: "",
            Sobkz: "E",
            Sonum: "0002266862000020",
            Squit: false,
            Tamea: "",
            Tamen: "",
            TamenTxt: "",
            Tanum: "",
            Tapos: "",
            Tbnum: "",
            Tbpos: "",
            Verme: "",
            VermeTxt: "1 PZ",
            Vlenr: "",
            Vlpla: "",
            Vltyp: "",
            Wdatu: "20250613",
            Werks: "3980",
          },
        },
      ]);
    },
  };
});
